---

- name: Make directory bash_completion.d
  file: >
    dest={{ bash_location }}
    state=directory
    mode=0755

- name: Download shell file
  get_url: >
    url={{ download_url }}/{{ item }}
    dest={{ bash_location }}
    mode=0444
  with_items:
  - git-completion.bash
  - git-prompt.sh
