---
- name: Download hub
  git: repo=https://github.com/github/hub.git
       dest="{{ hub_location }}/src/hub"
       version={{ hub_version }}

- name: Download hub
  get_url:
    url: "https://github.com/github/hub/releases/download/v{{ hub_version }}/hub-linux-amd64-{{ hub_version }}.tar.gz"
    dest: "{{ hub_location }}/hub-{{ hub_version }}.tar.gz"

- name: Build hub
  shell: /usr/bin/env PATH=$PATH ./script/build
  args:
    chdir: "{{ hub_location }}/src/hub"
    creates: "{{ hub_location }}/src/hub/hub"
  environment:
    PATH: "{{ go_location }}/bin:/usr/bin"

- name: Install hub
  command: cp hub "{{ hub_location }}/bin"
  args:
    chdir: "{{ hub_location }}/src/hub"
    creates: "{{ hub_location }}/bin/hub"

- name: Insert alias
  lineinfile: >
    dest="/home/{{ ansible_env.user }}/.bash_profile"
    create=yes
    state=present
    line='eval "$(hub alias -s)"'
